import type { ColumnSchema, ColumnType, RequestedIndex } from './types';

export class ColumnDefinition {
    /**
     * The name of the column.
     */
    readonly #name: string;

    /**
     * The declared type of the column.
     */
    readonly #type: ColumnType;

    /**
     * Whether the column accepts a null value.
     */
    #nullable: boolean = false;

    /**
     * The default value applied when the column is absent.
     */
    #default: unknown = undefined;

    /**
     * Whether a default value has been declared.
     */
    #hasDefault: boolean = false;

    /**
     * Whether the column is the key path of its table.
     */
    #primary: boolean = false;

    /**
     * Whether the column is generated by the database.
     */
    #increments: boolean = false;

    /**
     * The number of decimal places a scaled column carries.
     */
    #places: number | null = null;

    /**
     * The values an enumerated column accepts.
     */
    #values: string[] | null = null;

    /**
     * The indexes requested for the column.
     */
    readonly #requested: RequestedIndex[] = [];

    /**
     * Create a new column definition.
     */
    constructor(name: string, type: ColumnType) {
        this.#name = name;
        this.#type = type;
    }

    /**
     * Get the name of the column.
     */
    get name(): string {
        return this.#name;
    }

    /**
     * Get the declared type of the column.
     */
    get type(): ColumnType {
        return this.#type;
    }

    /**
     * Record the scale of a decimal column.
     */
    scaled(places: number): this {
        this.#places = places;

        return this;
    }

    /**
     * Record the values an enumerated column accepts.
     */
    accepts(values: string[]): this {
        this.#values = values;

        return this;
    }

    /**
     * Allow the column to hold a null value.
     */
    nullable(value: boolean = true): this {
        this.#nullable = value;

        return this;
    }

    /**
     * Set the value applied when the column is absent.
     */
    default(value: unknown): this {
        this.#default = value;
        this.#hasDefault = true;

        return this;
    }

    /**
     * Make the column the key path of its table.
     */
    primary(): this {
        this.#primary = true;

        return this;
    }

    /**
     * Let the database generate the column value.
     */
    increments(): this {
        this.#increments = true;

        return this;
    }

    /**
     * Request an index over the column.
     */
    index(name: string | null = null): this {
        this.#requested.push({ name, unique: false, multiEntry: false });

        return this;
    }

    /**
     * Request a unique index over the column.
     */
    unique(name: string | null = null): this {
        this.#requested.push({ name, unique: true, multiEntry: false });

        return this;
    }

    /**
     * Index each element of the column's array value, requesting an index when none was.
     */
    multiEntry(): this {
        if (this.#requested.length === 0) {
            this.index();
        }

        for (const requested of this.#requested) {
            requested.multiEntry = true;
        }

        return this;
    }

    /**
     * Get the indexes requested for the column.
     */
    requested(): RequestedIndex[] {
        return this.#requested;
    }

    /**
     * Get the schema describing the column.
     */
    toSchema(): ColumnSchema {
        return {
            name      : this.#name,
            type      : this.#type,
            nullable  : this.#nullable,
            default   : this.#default,
            hasDefault: this.#hasDefault,
            primary   : this.#primary,
            increments: this.#increments,
            places    : this.#places,
            values    : this.#values,
        };
    }
}
